r"""Reduce LaTeX column specifications to something pandoc can actually read.

This module is the ONE implementation of that operation. `render/pandoc.py`
calls it on the way into every HTML render, and the Word submission skills
(`~/.claude/skills/submission/pandoc-docx`, `docx-package`) import it rather
than carrying a copy. There was a second copy, standalone, in the skills; it had
already drifted, and the drift is recorded below under THE DIVERGENCE.

THE DEFECT THIS EXISTS FOR
--------------------------
`\newcolumntype` **with an arity argument**, appearing in the document BODY,
breaks pandoc::

    \newcolumntype{m}[1]{>{\centering\arraybackslash}p{#1}}

Pandoc's LaTeX reader has no handler for the arity. It consumes `{m}`, leaves
`[1]{...}` in the stream as content, and the `#1` is an illegal token. In the
PREAMBLE pandoc tolerates the declaration; in the BODY it does not. Verified
identical on pandoc 3.1.1 and 3.10.1 -- this is not a regression and waiting for
an upstream fix is not a plan.

It fails in two shapes, and the second is the dangerous one:

* **Hard error**, exit 64: `Error at "main.tex" (line 6, column 52): unexpected #1`
* **Exit 0 with silent damage.** `\newcolumntype{m}[1]{c}` parses, and the arity
  leaks into the body as visible prose: `Para [ Str "[1]", Span ... [ Str "c" ]]`.

Pandoc reports `\begin{document}` as the position for ANY error raised inside an
`\include`. That is a fallback, not the real location, and it is why this went
undiagnosed for so long. Do not trust pandoc's reported position.

These lines are machine-generated by the house R table-export scripts, so this
is an idiom rather than an accident and it will keep recurring: 140 body
occurrences across 70 files in estonia-ecm, 98 across 49 files in three projects
under ~/Documents/Papers.

WHY THE OBVIOUS FIX IS WORSE THAN NO FIX
----------------------------------------
Deleting the declarations is half the job, and shipping only that half converts
a loud failure into a silent one -- the worse of the two.

1. **The letters outlive the declaration.** `\begin{longtable}{R{4.0cm} M{2.2cm}
   M{2.2cm}}` still names `R` and `M` after the declarations are gone. Pandoc
   does not recognise them and does not complain: it emits a `Div` containing a
   `Para`, the column spec leaking as literal text and the data cells running
   together as prose separated by literal `&`, at exit 0. No table at all, and
   nothing in stderr.

2. **A redefinition can invert an alignment.** estonia-ecm declares
   `\newcolumntype{r}[1]{>{\raggedright\arraybackslash}p{#1}}` -- it redefines
   the BUILT-IN `r` to mean ragged-right, which is to say LEFT-aligned. Strip
   the declaration and `r` is still a legal pandoc column letter, so those
   columns render **right-aligned: backwards, silently, at exit 0, with the
   table intact so no structural guard fires.** This is why the alignment must
   be READ OUT of the declaration before stripping, and can never be guessed
   from the letter.

So the operation is a pair and the two halves must not be separated:
`declared_column_types` records what each letter meant, and `plain_table_specs`
/ `plain_multicolumn_specs` rewrite every spec that used it. `normalize_tables`
runs them in the one order that is correct.

THE DIVERGENCE, and why the copies were collapsed
-------------------------------------------------
Diffed on 2026-07-29 over 3,477 `.tex` files -- five manuscript repositories plus
the local papers archive -- the two implementations agreed on the declared
alignment map everywhere and disagreed on the output of eight files. All eight
were the same defect, and it was Manuscriptor's copy that was wrong. The skills'
copy rejoined a `\multicolumn` whose content group the author had put on the next
line;
Manuscriptor's did not, so estonia-ecm's balance table rendered as 29 bytes of
nothing. Measured on pandoc 3.1.1: without the rejoin, `<table>` count 0; with
it, 1. That is the whole argument for one implementation. The copy that is wrong
is the one nobody reads.

The second copy was written that same afternoon and collapsed about two hours
later, which sharpens the point rather than weakening it: two implementations of
this operation did not need months to disagree on real manuscripts. They needed
one sitting.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# Table environments, and how many mandatory arguments stand between
# `\begin{...}` and the column specification. `tabular*` and `tabularx` take a
# target width first; the rest go straight to the spec.
TABLE_ENVS = {
    "tabular": 0,
    "longtable": 0,
    "supertabular": 0,
    "tabular*": 1,
    "tabularx": 1,
    "xltabular": 1,
}

TABLE_BEGIN_RE = re.compile(
    r"\\begin\s*\{("
    + "|".join(re.escape(n) for n in sorted(TABLE_ENVS, key=len, reverse=True))
    + r")\}\s*"
)

NEWCOLUMNTYPE_RE = re.compile(r"\\newcolumntype\s*\{[^}]*\}\s*(?:\[[^\]]*\])?\s*")
MULTICOLUMN_RE = re.compile(r"\\multicolumn\s*\{[^}]*\}\s*(?=\{)")

# LaTeX column types reduced to the alignment pandoc can actually express.
ALIGN = {"c": "c", "l": "l", "r": "r", "m": "c", "p": "l", "b": "l", "X": "l"}

MANIFEST_SUFFIX = ".tables.json"


# --------------------------------------------------------------- public API


def normalize_tables(source: str) -> tuple[str, dict]:
    r"""Strip `\newcolumntype` declarations and repair every spec that used one.

    Returns `(text, stats)`, where `stats` carries `declarations`,
    `table_specs`, `multicolumn_specs`, `declared` (the letter -> alignment map
    recovered) and `alignments` (what the source asks for, per table).

    The order is the whole point and is not negotiable: read the alignments,
    THEN strip, THEN rewrite the specs using what was read. Reordering it, or
    dropping any step, is the silent-damage path described in the module
    docstring.
    """
    declared = declared_column_types(source)
    # Recorded BEFORE anything is stripped. This is the only moment at which
    # what the author meant is still on disk, and the post-conversion alignment
    # gate has nothing to check against without it. Compare the delivered docx
    # to a file that has ALREADY been stripped and a naive strip-only
    # normalization looks self-consistent -- the intermediate says `r` and the
    # docx says right-aligned, and they agree with each other while both
    # contradict the manuscript.
    alignments = expected_alignments(source)
    source, declarations = strip_newcolumntypes(source)
    source, multicolumn_specs = plain_multicolumn_specs(source, declared)
    source, table_specs = plain_table_specs(source, declared)
    return source, {
        "declarations": declarations,
        "table_specs": table_specs,
        "multicolumn_specs": multicolumn_specs,
        "declared": declared,
        "alignments": alignments,
    }


def declared_column_types(source: str) -> dict[str, str]:
    r"""Read the alignment out of each `\newcolumntype` before dropping it.

    Guessing would be wrong on the reference manuscript, which redefines `r` as
    ragged-*right*, i.e. left-aligned. The declaration says so; there is no
    reason to infer what the source states.
    """
    declared: dict[str, str] = {}
    for m in re.finditer(r"\\newcolumntype\s*\{([^}]*)\}\s*(?:\[[^\]]*\])?", source):
        name = m.group(1).strip()
        if len(name) != 1:
            continue
        end = skip_group(source, m.end())
        body = source[m.end():end]
        if "\\centering" in body:
            declared[name] = "c"
        elif "\\raggedleft" in body:
            declared[name] = "r"
        elif "\\raggedright" in body:
            declared[name] = "l"
        else:
            base = re.search(r"\\?\b([pmbclr])\s*\{", body)
            declared[name] = ALIGN.get(base.group(1), "l") if base else "l"
    return declared


def strip_newcolumntypes(source: str) -> tuple[str, int]:
    r"""Delete each declaration, arity spec and brace-balanced body included.

    `\newcolumntype{m}[1]{>{\centering}p{#1}}` -- the `#1` is what breaks
    pandoc. The body is matched by counting braces rather than by a `[^}]*`
    regex, because `>{\centering\arraybackslash}p{#1}` contains two nested
    groups and a lazy match would cut it in half, leaving a stray `}p{#1}}`
    that is worse than the line it replaced.
    """
    out: list[str] = []
    cursor = 0
    count = 0
    while True:
        m = NEWCOLUMNTYPE_RE.search(source, cursor)
        if m is None:
            out.append(source[cursor:])
            return "".join(out), count
        out.append(source[cursor:m.start()])
        end = skip_group(source, m.end())
        if end < len(source) and source[end] == "\n":
            end += 1
        cursor = end
        count += 1


def plain_table_specs(source: str, declared: dict[str, str] | None = None
                      ) -> tuple[str, int]:
    r"""`\begin{tabular}{R{4cm} M{2cm}}` becomes `\begin{tabular}{lc}`.

    Load-bearing rather than tidy. `R` and `M` come from the `\newcolumntype`
    declarations stripped above, and a column type pandoc does not recognise
    makes it drop the ENTIRE table at exit 0. Removing the declarations without
    also reducing the specs that used them trades a loud failure for a silent
    one, which is the worse of the two.
    """
    out: list[str] = []
    cursor = 0
    count = 0
    while True:
        m = TABLE_BEGIN_RE.search(source, cursor)
        if m is None:
            out.append(source[cursor:])
            return "".join(out), count
        at = skip_optional(source, m.end())
        for _ in range(TABLE_ENVS[m.group(1)]):
            at = skip_group(source, at)
        spec_end = skip_group(source, at)
        start = group_start(source, at)
        if spec_end == at or start is None:
            out.append(source[cursor:m.end()])
            cursor = m.end()
            continue
        out.append(source[cursor:start])
        out.append("{" + plain_colspec(source[start + 1:spec_end - 1], declared) + "}")
        cursor = spec_end
        count += 1


def plain_multicolumn_specs(source: str, declared: dict[str, str] | None = None
                            ) -> tuple[str, int]:
    r"""`\multicolumn{2}{m{3.4cm}}{X}` becomes `\multicolumn{2}{c}{X}`.

    A width-bearing `\multicolumn` spec costs the whole table, silently, the
    same way an unknown column letter does.

    This also pulls the content argument back onto the spec's own line. Pandoc's
    reader will not carry a `\multicolumn` across a newline between its spec and
    its content::

        \multicolumn{2}{c}
        {\textbf{Means}}

    parses as no table at all -- `Div` + `Para`, column spec leaking as literal
    text, exit 0 -- while the identical row written on one line parses fine.
    Verified on pandoc 3.1.1. This is how estonia-ecm's balance table was still
    being lost after every column type in it had been normalized, so the rejoin
    belongs here, next to the other half of the same repair. It is also the one
    thing the two implementations disagreed about; see THE DIVERGENCE above.
    """
    out: list[str] = []
    cursor = 0
    count = 0
    while True:
        m = MULTICOLUMN_RE.search(source, cursor)
        if m is None:
            out.append(source[cursor:])
            return "".join(out), count
        spec_end = skip_group(source, m.end())
        if spec_end == m.end():
            out.append(source[cursor:m.end()])
            cursor = m.end()
            continue
        spec = source[m.end() + 1:spec_end - 1]
        out.append(source[cursor:m.end()])
        out.append("{" + plain_colspec(spec, declared) + "}")
        cursor = spec_end
        # Close the gap to the content group, if the author broke the line.
        gap = spec_end
        while gap < len(source) and source[gap] in " \t\r\n":
            gap += 1
        if gap < len(source) and source[gap] == "{" and "\n" in source[spec_end:gap]:
            cursor = gap
        count += 1


_COMMENT_RE = re.compile(r"(?<!\\)((?:\\\\)*)%[^\n]*")


def strip_comments(text: str) -> str:
    r"""Drop LaTeX comments, leaving escaped `\%` and `\\` alone.

    `\%` is a literal percent sign and starts nothing; `\\%` IS a comment,
    because the backslashes pair off first. The capture group preserves any
    even-numbered run of backslashes that preceded the `%`.
    """
    return _COMMENT_RE.sub(r"\1", text)


def count_table_environments(text: str) -> int:
    r"""How many table environments the LaTeX source actually contains.

    The unit of the post-conversion count guard. Counts the tabular-family
    environments rather than `\begin{table}`, because a float may hold none or
    several and it is the tabular that becomes a table in the output.

    Comments are stripped first. Authors leave superseded column specs commented
    out directly above the live one -- estonia-ecm's balance table carries two
    such ghosts -- and counting them inflates the expected total, which fires
    the guard on a document that is perfectly fine. A guard that cries wolf gets
    switched off, so a false alarm is a real defect and not a safe direction to
    err in.
    """
    return len(TABLE_BEGIN_RE.findall(strip_comments(text)))


_WORD_ALIGN = {"l": "left", "c": "center", "r": "right"}


def expected_alignments(text: str) -> list[list[str]]:
    r"""Per-table column alignments the SOURCE asks for, in document order.

    A list of lists of `"left"`/`"center"`/`"right"`, one per table environment,
    read through the same `\newcolumntype` map the normalizer uses. This is what
    a delivered `.docx` must actually contain: the docx is submitted from, and a
    column silently flipped to right-aligned reads as a formatting choice rather
    than an error, so it survives a human skim all the way to the journal.

    Vertical rules are dropped -- they are not columns.
    """
    declared = declared_column_types(text)
    body = strip_comments(text)
    out: list[list[str]] = []
    for m in TABLE_BEGIN_RE.finditer(body):
        at = skip_optional(body, m.end())
        for _ in range(TABLE_ENVS[m.group(1)]):
            at = skip_group(body, at)
        spec_end = skip_group(body, at)
        start = group_start(body, at)
        if spec_end == at or start is None:
            out.append([])
            continue
        letters = plain_colspec(body[start + 1:spec_end - 1], declared)
        out.append([_WORD_ALIGN[c] for c in letters if c in _WORD_ALIGN])
    return out


_REPEAT_RE = re.compile(r"\*\s*\{\s*(\d+)\s*\}\s*(?=\{)")


def _expand_repeats(spec: str) -> str:
    r"""Expand the `array` package's `*{n}{cols}` repetition.

    This is what Stata's esttab emits by default (`l*{1}{ccccc}`), and pandoc
    does not read it: the table vanishes with no error. estonia-qbs lost five of
    its seven tables to exactly this.

    Dropping the multiplier instead of expanding it is worse than it looks. At
    `*{1}` it happens to be right, so it passes on the common case and then
    quietly discards columns the moment a manuscript uses `*{3}`.
    """
    out = spec
    for _ in range(8):  # bounded: nested repeats are legal but never deep
        m = _REPEAT_RE.search(out)
        if not m:
            break
        end = skip_group(out, m.end())
        inner = out[m.end() + 1:end - 1]
        out = out[:m.start()] + inner * int(m.group(1)) + out[end:]
    return out


def plain_colspec(spec: str, declared: dict[str, str] | None = None) -> str:
    r"""Reduce a column specification to alignment letters and rules.

    Pandoc's tables carry alignment and nothing else, so width, font, and
    inter-column material are all noise. The reduction has to be a parse rather
    than a substitution: `>{\centering\arraybackslash}p{4cm}` contains the
    letters c, r, and l inside a command name, and a character filter would read
    that single column as four.
    """
    spec = _expand_repeats(spec)
    out: list[str] = []
    i = 0
    while i < len(spec):
        c = spec[i]
        if c in "<>@!":
            nxt = skip_group(spec, i + 1)
            i = nxt if nxt > i + 1 else i + 1
            continue
        if c == "[":
            i = skip_optional(spec, i)
            continue
        if c == "|":
            out.append("|")
            i += 1
            continue
        if c.isalpha():
            after = skip_optional(spec, i + 1)
            after = skip_group(spec, after)
            out.append((declared or {}).get(c) or ALIGN.get(c, "l"))
            i = max(after, i + 1)
            continue
        i += 1
    return "".join(out) or "l"


# ------------------------------------------------------- the manifest
#
# Written beside the normalized `.tex` so a post-conversion gate can compare the
# delivered file against what the SOURCE asked for. Without it the gate can only
# compare against an already-stripped file, which cannot detect a strip-only
# normalization -- see the comment in `normalize_tables`.


def write_manifest(out_tex_path, stats: dict) -> Path:
    """Record the source's own alignments beside the normalized `.tex`."""
    path = Path(str(out_tex_path) + MANIFEST_SUFFIX)
    path.write_text(json.dumps({
        "alignments": stats["alignments"],
        "declared": stats["declared"],
    }, indent=1), encoding="utf-8")
    return path


def read_manifest(tex_path) -> dict | None:
    """The manifest beside `tex_path`, or None when it was never written."""
    path = Path(str(tex_path) + MANIFEST_SUFFIX)
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


# ------------------------------------------------- shared LaTeX brace helpers
#
# Not table logic, but every caller of the above needs them and `render/pandoc.py`
# uses the same three to unwrap `\resizebox` and to strip macro definitions.
# They live at the bottom of the module the other users import, rather than in a
# fourth module holding three functions.


def group_start(text: str, at: int) -> int | None:
    i = at
    while i < len(text) and text[i] in " \t\n":
        i += 1
    return i if i < len(text) and text[i] == "{" else None


def skip_optional(text: str, at: int) -> int:
    i = at
    while i < len(text) and text[i] in " \t":
        i += 1
    if i >= len(text) or text[i] != "[":
        return at
    depth = 0
    while i < len(text):
        if text[i] == "[":
            depth += 1
        elif text[i] == "]":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return at


def skip_group(text: str, at: int) -> int:
    r"""Return the offset just past the brace group starting at or after `at`.

    Comments are skipped, because LaTeX skips them and flattening does not strip
    them. A `%` line carrying a lone brace is legal source, and counting it
    would close a group somewhere in the middle of the table it wraps.

    A newline before the brace is skipped too, and an unbalanced group returns
    `at` -- no progress -- rather than the end of the text. Both were points on
    which the two implementations differed. `at` is what every caller here is
    written to expect: each of them tests `end == at` and leaves the construct
    alone, whereas `len(text)` makes an unclosed brace swallow the remainder of
    the document as though it were a column specification.
    """
    i = at
    while i < len(text) and text[i] in " \t\n":
        i += 1
    if i >= len(text) or text[i] != "{":
        return at
    depth = 0
    while i < len(text):
        c = text[i]
        if c == "%":
            nl = text.find("\n", i)
            i = len(text) if nl == -1 else nl + 1
            continue
        if c == "\\" and i + 1 < len(text):
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return at


# ------------------------------------------------------------------ the CLI
#
# `python3 -m manuscriptor.render.tables IN.tex [OUT.tex]`. The Word skills call
# this, and their scripts import the functions above directly.


def _cli(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.exit("usage: python3 -m manuscriptor.render.tables IN.tex [OUT.tex]")
    text = Path(argv[1]).read_text(encoding="utf-8", errors="replace")
    out, stats = normalize_tables(text)
    if len(argv) > 2:
        Path(argv[2]).write_text(out, encoding="utf-8")
        write_manifest(argv[2], stats)
        sys.stderr.write(
            "tables: stripped %d \\newcolumntype declaration(s), rewrote %d "
            "table spec(s) and %d \\multicolumn spec(s)\n"
            % (stats["declarations"], stats["table_specs"],
               stats["multicolumn_specs"]))
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli(sys.argv))
