r"""Repair what pandoc cannot read in a LaTeX table's structure.

Two repairs live here, and the invariant covering them was widened from the
first to both on 2026-08-03:

* **Column-type normalization**, the original and the subject of everything
  below -- `\newcolumntype` and the specs that used it.
* **Header-row identification** (`mark_header_rows`), further down under its own
  heading -- pandoc promotes at most ONE row into `<thead>`, so a header two
  rows deep arrives as body rows.

They are one module because they answer the same question -- what does this
LaTeX table actually say -- and both can only be answered while the LaTeX still
says it. Once pandoc has run, the `\newcolumntype` is gone and so are the rules
that fenced off the header.

This module is the ONE implementation of both. `render/pandoc.py`
calls it on the way into every HTML render, and the Word submission skills
(`~/.claude/skills/submission/pandoc-docx`, `docx-package`) import it rather
than carrying a copy. There was a second copy, standalone, in the skills; it had
already drifted, and the drift is recorded below under THE DIVERGENCE.

THE DEFECT THIS EXISTS FOR
--------------------------
`\newcolumntype` **with an arity argument**, appearing in the document BODY,
breaks pandoc::

    \newcolumntype{m}[1]{>{\centering\arraybackslash}p{#1}}

Pandoc's LaTeX reader has no handler for the arity. It consumes `{m}`, leaves
`[1]{...}` in the stream as content, and the `#1` is an illegal token. In the
PREAMBLE pandoc tolerates the declaration; in the BODY it does not. Verified
identical on pandoc 3.1.1 and 3.10.1 -- this is not a regression and waiting for
an upstream fix is not a plan.

It fails in two shapes, and the second is the dangerous one:

* **Hard error**, exit 64: `Error at "main.tex" (line 6, column 52): unexpected #1`
* **Exit 0 with silent damage.** `\newcolumntype{m}[1]{c}` parses, and the arity
  leaks into the body as visible prose: `Para [ Str "[1]", Span ... [ Str "c" ]]`.

Pandoc reports `\begin{document}` as the position for ANY error raised inside an
`\include`. That is a fallback, not the real location, and it is why this went
undiagnosed for so long. Do not trust pandoc's reported position.

These lines are machine-generated by the house R table-export scripts, so this
is an idiom rather than an accident and it will keep recurring: 140 body
occurrences across 70 files in estonia-ecm, 98 across 49 files in three projects
under ~/Documents/Papers.

WHY THE OBVIOUS FIX IS WORSE THAN NO FIX
----------------------------------------
Deleting the declarations is half the job, and shipping only that half converts
a loud failure into a silent one -- the worse of the two.

1. **The letters outlive the declaration.** `\begin{longtable}{R{4.0cm} M{2.2cm}
   M{2.2cm}}` still names `R` and `M` after the declarations are gone. Pandoc
   does not recognise them and does not complain: it emits a `Div` containing a
   `Para`, the column spec leaking as literal text and the data cells running
   together as prose separated by literal `&`, at exit 0. No table at all, and
   nothing in stderr.

2. **A redefinition can invert an alignment.** estonia-ecm declares
   `\newcolumntype{r}[1]{>{\raggedright\arraybackslash}p{#1}}` -- it redefines
   the BUILT-IN `r` to mean ragged-right, which is to say LEFT-aligned. Strip
   the declaration and `r` is still a legal pandoc column letter, so those
   columns render **right-aligned: backwards, silently, at exit 0, with the
   table intact so no structural guard fires.** This is why the alignment must
   be READ OUT of the declaration before stripping, and can never be guessed
   from the letter.

So the operation is a pair and the two halves must not be separated:
`declared_column_types` records what each letter meant, and `plain_table_specs`
/ `plain_multicolumn_specs` rewrite every spec that used it. `normalize_tables`
runs them in the one order that is correct.

THE DIVERGENCE, and why the copies were collapsed
-------------------------------------------------
Diffed on 2026-07-29 over 3,477 `.tex` files -- five manuscript repositories plus
the local papers archive -- the two implementations agreed on the declared
alignment map everywhere and disagreed on the output of eight files. All eight
were the same defect, and it was Manuscriptor's copy that was wrong. The skills'
copy rejoined a `\multicolumn` whose content group the author had put on the next
line;
Manuscriptor's did not, so estonia-ecm's balance table rendered as 29 bytes of
nothing. Measured on pandoc 3.1.1: without the rejoin, `<table>` count 0; with
it, 1. That is the whole argument for one implementation. The copy that is wrong
is the one nobody reads.

The second copy was written that same afternoon and collapsed about two hours
later, which sharpens the point rather than weakening it: two implementations of
this operation did not need months to disagree on real manuscripts. They needed
one sitting.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# Table environments, and how many mandatory arguments stand between
# `\begin{...}` and the column specification. `tabular*` and `tabularx` take a
# target width first; the rest go straight to the spec.
TABLE_ENVS = {
    "tabular": 0,
    "longtable": 0,
    "supertabular": 0,
    "tabular*": 1,
    "tabularx": 1,
    "xltabular": 1,
}

TABLE_BEGIN_RE = re.compile(
    r"\\begin\s*\{("
    + "|".join(re.escape(n) for n in sorted(TABLE_ENVS, key=len, reverse=True))
    + r")\}\s*"
)

NEWCOLUMNTYPE_RE = re.compile(r"\\newcolumntype\s*\{[^}]*\}\s*(?:\[[^\]]*\])?\s*")
MULTICOLUMN_RE = re.compile(r"\\multicolumn\s*\{[^}]*\}\s*(?=\{)")

# LaTeX column types reduced to the alignment pandoc can actually express.
ALIGN = {"c": "c", "l": "l", "r": "r", "m": "c", "p": "l", "b": "l", "X": "l"}

MANIFEST_SUFFIX = ".tables.json"

# The mark a header row carries through pandoc. It uses the sentinel brackets
# because those are the proven carrier in this codebase (`source/anchors.py`),
# and it spells no hex, so `anchors.MARKER_RE` can never mistake one for a block
# marker -- the same reasoning as `pandoc.TITLE_TOKEN`.
HEADER_TOKEN = "⟦MXTHEAD⟧"


# --------------------------------------------------------------- public API


def normalize_tables(source: str) -> tuple[str, dict]:
    r"""Strip `\newcolumntype` declarations and repair every spec that used one.

    Returns `(text, stats)`, where `stats` carries `declarations`,
    `table_specs`, `multicolumn_specs`, `declared` (the letter -> alignment map
    recovered) and `alignments` (what the source asks for, per table).

    The order is the whole point and is not negotiable: read the alignments,
    THEN strip, THEN rewrite the specs using what was read. Reordering it, or
    dropping any step, is the silent-damage path described in the module
    docstring.
    """
    declared = declared_column_types(source)
    # Recorded BEFORE anything is stripped. This is the only moment at which
    # what the author meant is still on disk, and the post-conversion alignment
    # gate has nothing to check against without it. Compare the delivered docx
    # to a file that has ALREADY been stripped and a naive strip-only
    # normalization looks self-consistent -- the intermediate says `r` and the
    # docx says right-aligned, and they agree with each other while both
    # contradict the manuscript.
    alignments = expected_alignments(source)
    source, declarations = strip_newcolumntypes(source)
    source, multicolumn_specs = plain_multicolumn_specs(source, declared)
    source, table_specs = plain_table_specs(source, declared)
    return source, {
        "declarations": declarations,
        "table_specs": table_specs,
        "multicolumn_specs": multicolumn_specs,
        "declared": declared,
        "alignments": alignments,
    }


def declared_column_types(source: str) -> dict[str, str]:
    r"""Read the alignment out of each `\newcolumntype` before dropping it.

    Guessing would be wrong on the reference manuscript, which redefines `r` as
    ragged-*right*, i.e. left-aligned. The declaration says so; there is no
    reason to infer what the source states.
    """
    declared: dict[str, str] = {}
    for m in re.finditer(r"\\newcolumntype\s*\{([^}]*)\}\s*(?:\[[^\]]*\])?", source):
        name = m.group(1).strip()
        if len(name) != 1:
            continue
        end = skip_group(source, m.end())
        body = source[m.end():end]
        if "\\centering" in body:
            declared[name] = "c"
        elif "\\raggedleft" in body:
            declared[name] = "r"
        elif "\\raggedright" in body:
            declared[name] = "l"
        else:
            base = re.search(r"\\?\b([pmbclr])\s*\{", body)
            declared[name] = ALIGN.get(base.group(1), "l") if base else "l"
    return declared


def strip_newcolumntypes(source: str) -> tuple[str, int]:
    r"""Delete each declaration, arity spec and brace-balanced body included.

    `\newcolumntype{m}[1]{>{\centering}p{#1}}` -- the `#1` is what breaks
    pandoc. The body is matched by counting braces rather than by a `[^}]*`
    regex, because `>{\centering\arraybackslash}p{#1}` contains two nested
    groups and a lazy match would cut it in half, leaving a stray `}p{#1}}`
    that is worse than the line it replaced.
    """
    out: list[str] = []
    cursor = 0
    count = 0
    while True:
        m = NEWCOLUMNTYPE_RE.search(source, cursor)
        if m is None:
            out.append(source[cursor:])
            return "".join(out), count
        out.append(source[cursor:m.start()])
        end = skip_group(source, m.end())
        if end < len(source) and source[end] == "\n":
            end += 1
        cursor = end
        count += 1


def plain_table_specs(source: str, declared: dict[str, str] | None = None
                      ) -> tuple[str, int]:
    r"""`\begin{tabular}{R{4cm} M{2cm}}` becomes `\begin{tabular}{lc}`.

    Load-bearing rather than tidy. `R` and `M` come from the `\newcolumntype`
    declarations stripped above, and a column type pandoc does not recognise
    makes it drop the ENTIRE table at exit 0. Removing the declarations without
    also reducing the specs that used them trades a loud failure for a silent
    one, which is the worse of the two.
    """
    out: list[str] = []
    cursor = 0
    count = 0
    while True:
        m = TABLE_BEGIN_RE.search(source, cursor)
        if m is None:
            out.append(source[cursor:])
            return "".join(out), count
        at = skip_optional(source, m.end())
        for _ in range(TABLE_ENVS[m.group(1)]):
            at = skip_group(source, at)
        spec_end = skip_group(source, at)
        start = group_start(source, at)
        if spec_end == at or start is None:
            out.append(source[cursor:m.end()])
            cursor = m.end()
            continue
        out.append(source[cursor:start])
        out.append("{" + plain_colspec(source[start + 1:spec_end - 1], declared) + "}")
        cursor = spec_end
        count += 1


def plain_multicolumn_specs(source: str, declared: dict[str, str] | None = None
                            ) -> tuple[str, int]:
    r"""`\multicolumn{2}{m{3.4cm}}{X}` becomes `\multicolumn{2}{c}{X}`.

    A width-bearing `\multicolumn` spec costs the whole table, silently, the
    same way an unknown column letter does.

    This also pulls the content argument back onto the spec's own line. Pandoc's
    reader will not carry a `\multicolumn` across a newline between its spec and
    its content::

        \multicolumn{2}{c}
        {\textbf{Means}}

    parses as no table at all -- `Div` + `Para`, column spec leaking as literal
    text, exit 0 -- while the identical row written on one line parses fine.
    Verified on pandoc 3.1.1. This is how estonia-ecm's balance table was still
    being lost after every column type in it had been normalized, so the rejoin
    belongs here, next to the other half of the same repair. It is also the one
    thing the two implementations disagreed about; see THE DIVERGENCE above.
    """
    out: list[str] = []
    cursor = 0
    count = 0
    while True:
        m = MULTICOLUMN_RE.search(source, cursor)
        if m is None:
            out.append(source[cursor:])
            return "".join(out), count
        spec_end = skip_group(source, m.end())
        if spec_end == m.end():
            out.append(source[cursor:m.end()])
            cursor = m.end()
            continue
        spec = source[m.end() + 1:spec_end - 1]
        out.append(source[cursor:m.end()])
        out.append("{" + plain_colspec(spec, declared) + "}")
        cursor = spec_end
        # Close the gap to the content group, if the author broke the line.
        gap = spec_end
        while gap < len(source) and source[gap] in " \t\r\n":
            gap += 1
        if gap < len(source) and source[gap] == "{" and "\n" in source[spec_end:gap]:
            cursor = gap
        count += 1


# ------------------------------------------------------- header-row marking
#
# The second table-structure repair in this module, and a clearly separate
# operation from the column-type pair above. It is here because both are LaTeX
# table structure, decided where the LaTeX still says what it means.
#
# THE DEFECT
# ----------
# Pandoc's LaTeX reader promotes at most ONE row into the header. Measured on
# pandoc 3.10.1::
#
#     one header row  + \hline  ->  <thead><tr><th> ...   promoted
#     two header rows + \hline  ->  <tbody><tr><td> ...   nothing promoted
#
# So a table whose header is two rows deep -- a span label over the column
# numbers, which is how nearly every regression table is written -- comes back
# as body rows only. The headers are not missing from the page; they are sitting
# in it as ordinary data cells, which is why this survived being looked at. What
# is missing is the `<thead>`, and with it every sticky-header and header-rule
# rule in the stylesheet. 72 of the corpus's 243 tables declare two or more:
# 10 of estonia-ecm's 82, 1 of estonia-qbs's 7, 57 of qutub-india's 117, 4 of
# covet-india's 5, 0 of dsp-bias's 32.
#
# WHY IT IS DECIDED HERE AND NOT IN THE HTML
# ------------------------------------------
# In the LaTeX the answer is written down: the header is the rows the author
# fenced off with a full-width rule. In the HTML it is gone, and anything done
# there is a guess about what a row looks like -- which covet-india's Table 1
# defeats immediately, since it puts `\multicolumn{6}{l}{\textit{Patna}}` in the
# middle of the body as a panel label. It is indistinguishable from a header row
# by content and is not one. `render/postprocess.py` may only CARRY this
# marking; it must never infer it.
#
# WHERE THE MARK GOES, WHICH IS NOT WHERE IT LOOKS LIKE IT SHOULD
# ---------------------------------------------------------------
# At the head of the row's FIRST CELL -- except that a cell beginning with
# `\multicolumn` is a spanning cell to pandoc, and putting anything in front of
# it costs both the span and the text inside it. Measured::
#
#     ⟦MXTHEAD⟧\multicolumn{2}{c}{Panel} & C \\
#         ->  <td>⟦MXTHEAD⟧</td><td>C</td><td></td>
#
# `Panel` gone, colspan gone, at exit 0 -- the silent shape again. So the mark
# descends into the content group of a leading `\multicolumn` or `\multirow`,
# where it is ordinary cell text and the construct is untouched.

_ROW_SEP_RE = re.compile(r"\\\\\s*\*?\s*(?:\[[^\]]*\])?")

# Full-width rules only. `\cmidrule` and `\cline` underline a SPAN of a header
# and do not close one -- `\toprule / span label / \cmidrule(lr){2-3} / column
# numbers / \midrule` is the standard booktabs header, and reading the partial
# rule as a boundary would leave the column numbers in the body, which is the
# one row a reader most needs to see in the header.
_FULL_RULE_RE = re.compile(r"\\(?:hline|toprule|midrule|bottomrule)\b\s*(?:\[[^\]]*\])?")

# Row material that is syntax rather than cells. A longtable's first row is
# `\caption{...} \\`, and reading it as the header would put the caption in
# `<thead>` and leave the real header in the body.
_NOT_CELLS_RE = re.compile(
    r"\\(?:endfirsthead|endhead|endfoot|endlastfoot|nopagebreak|centering)\b|"
    r"\\noalign\s*\{[^{}]*\}"
)

# The caption is taken out by brace counting rather than by `\{[^{}]*\}`, and
# that is not a nicety. estonia-ecm writes `\caption{\textbf{ECM Impact:} On
# patient's care (ANCOVA)}`, and the flat pattern cannot read it: the caption
# row then looked like a row with cells, became the header block, and the two
# real header rows below it stayed in the body. It cost 13 of that manuscript's
# 17 tables and failed in total silence -- the mark landed in the caption, where
# there is no `<tr>` to promote, so the table rendered exactly as it had before.
_CAPTION_RE = re.compile(r"\\(?:caption|label)\s*\*?\s*(?=[\[{])")


def _drop_captions(text: str) -> str:
    out: list[str] = []
    i = 0
    while True:
        m = _CAPTION_RE.search(text, i)
        if m is None:
            out.append(text[i:])
            return "".join(out)
        out.append(text[i:m.start()])
        at = skip_optional(text, m.end())
        end = skip_group(text, at)
        i = end if end > at else m.end()

# A cell that opens with one of these hands its content to a trailing group, and
# the mark belongs inside it. Both take two mandatory arguments before it.
_SPANNING_CELL_RE = re.compile(r"\\(?:multicolumn|multirow)\s*(?=[\[{])")

_CONTROL_RE = re.compile(r"\\[A-Za-z@]+\*?|\\.", re.S)


def mark_header_rows(source: str) -> tuple[str, int]:
    r"""Mark each table's header rows with `HEADER_TOKEN`, before pandoc reads them.

    Returns `(text, rows_marked)` -- ROWS, not marks. A row carries one mark per
    cell (see `_header_marks`), and the count that means anything to a caller is
    how many rows were called headers. Identification is deterministic and comes
    entirely from the rules the author wrote: the header is the first run of
    rows fenced off by full-width rules, and a table with no rule, or with no
    body after that fence, has no header and gains no mark. See the block
    comment above for why this cannot be decided after the render.
    """
    edits: list[int] = []
    rows_marked = 0
    cursor = 0
    while True:
        m = TABLE_BEGIN_RE.search(source, cursor)
        if m is None:
            break
        if _commented(source, m.start()):
            cursor = m.end()
            continue
        at = skip_optional(source, m.end())
        for _ in range(TABLE_ENVS[m.group(1)]):
            at = skip_group(source, at)
        body_start = skip_group(source, at)
        if body_start == at:
            cursor = m.end()
            continue
        body_end = _environment_end(source, m.group(1), body_start)
        per_row = _header_marks(source, body_start, body_end)
        rows_marked += len(per_row)
        edits.extend(at for row in per_row for at in row)
        cursor = body_end

    if not edits:
        return source, 0
    out: list[str] = []
    prev = 0
    for at in sorted(edits):
        out.append(source[prev:at])
        out.append(HEADER_TOKEN)
        prev = at
    out.append(source[prev:])
    return "".join(out), rows_marked


def _environment_end(source: str, name: str, at: int) -> int:
    r"""The offset of this environment's own `\end{name}`, counting nested ones.

    Commented begins and ends do not count, and that is the whole reason this
    is not a `source.find("\\end{...}")`. Authors leave a superseded table
    commented out directly above or inside the live one -- the same habit
    `count_table_environments` strips comments for -- and one commented
    `\begin{longtable}` raised the depth here far enough that the scan ran off
    the end of estonia-ecm, taking the cursor with it. One table was seen; the
    other sixteen were never looked at.
    """
    pattern = re.compile(r"\\(begin|end)\s*\{" + re.escape(name) + r"\}")
    depth = 0
    for m in pattern.finditer(source, at):
        if _commented(source, m.start()):
            continue
        if m.group(1) == "begin":
            depth += 1
        elif depth == 0:
            return m.start()
        else:
            depth -= 1
    return len(source)


def _commented(source: str, at: int) -> bool:
    """Does an unescaped `%` stand between the start of this line and `at`?"""
    line = source.rfind("\n", 0, at) + 1
    return _COMMENT_RE.search(source[line:at]) is not None


def _header_marks(source: str, start: int, stop: int) -> list[list[int]]:
    """Offsets at which a header token must be inserted, one list per header row."""
    segments = _rule_segments(source, start, stop)
    rows = [_cell_rows(source, lo, hi) for lo, hi in segments]
    head = next((i for i, r in enumerate(rows) if r), None)
    if head is None:
        return []                      # no rows with cells at all
    if not any(rows[head + 1:]):
        # Nothing below the fence. `\toprule / rows / \bottomrule` with no
        # `\midrule` declares no header -- there is nothing for one to stand
        # over -- and pandoc emits no `<thead>` for it either.
        return []
    marks: list[list[int]] = []
    for lo, hi in rows[head]:
        # EVERY cell of the row, not just the first. A `\multirow{2}{*}{...}`
        # opening the header makes pandoc emit `rowspan="2"` and the row below
        # it has no first cell at all -- it was absorbed -- so a mark placed
        # only at the head of each row disappears for that row and promotion
        # stops above it. estonia-ecm's regression tables all open that way, and
        # a three-row header arrived one row deep.
        row = [
            at for at in (_mark_offset(source, a, b) for a, b in _cells(source, lo, hi))
            # A cell whose spanning construct could not be read is skipped
            # rather than marked at its head: the row still carries the marks of
            # its other cells, while a mark in front of a `\multicolumn` costs
            # the span and the words inside it.
            if at is not None
        ]
        if row:
            marks.append(row)
    return marks


def _cells(source: str, start: int, stop: int) -> list[tuple[int, int]]:
    """The spans of one row's cells, split at the top-level `&`."""
    out: list[tuple[int, int]] = []
    at = start
    for lo, hi, kind in _top_level(source, start, stop):
        if kind == "cell":
            out.append((at, lo))
            at = hi
    out.append((at, stop))
    return out


def _rule_segments(source: str, start: int, stop: int) -> list[tuple[int, int]]:
    """The body cut at every top-level full-width rule.

    Consecutive rules yield an empty segment between them, which is what makes
    `\\hline\\hline` -- one boundary written twice -- fall out correctly rather
    than being read as an empty header block.
    """
    cuts: list[tuple[int, int]] = []
    for lo, hi, kind in _top_level(source, start, stop):
        if kind == "rule":
            cuts.append((lo, hi))
    out: list[tuple[int, int]] = []
    at = start
    for lo, hi in cuts:
        out.append((at, lo))
        at = hi
    out.append((at, stop))
    return out


def _cell_rows(source: str, start: int, stop: int) -> list[tuple[int, int]]:
    """The spans of the rows in one segment that actually carry cells."""
    rows: list[tuple[int, int]] = []
    at = start
    for lo, hi, kind in _top_level(source, start, stop):
        if kind == "rowsep":
            rows.append((at, lo))
            at = hi
    # Whatever trails the last `\\` is not a row: LaTeX's final row separator is
    # optional, so it is either the last row or nothing, and it is the last row
    # only when it carries cells. `_has_cells` decides that either way.
    rows.append((at, stop))
    return [(lo, hi) for lo, hi in rows if _has_cells(source, lo, hi)]


def _has_cells(source: str, start: int, stop: int) -> bool:
    text = _drop_captions(strip_comments(source[start:stop]))
    return bool(_NOT_CELLS_RE.sub("", text).strip())


def _mark_offset(source: str, start: int, stop: int) -> int | None:
    """Where the token goes in this row: the head of its first cell's content.

    Descends through a leading `\\multicolumn`/`\\multirow` into its content
    group, brace-counting rather than pattern-matching, because a spec may
    itself contain braces. `None` when the descent cannot be made, which the
    caller reads as "leave this row alone" -- see `_header_marks`.
    """
    at = start
    while at < stop:
        if source[at] in " \t\r\n":
            at += 1
            continue
        if source[at] == "%":
            nl = source.find("\n", at)
            at = stop if nl == -1 else min(nl + 1, stop)
            continue
        m = _SPANNING_CELL_RE.match(source, at)
        if m is None:
            return at
        after = m.end()
        for _ in range(2):             # the two mandatory arguments
            after = skip_optional(source, after)
            nxt = skip_group(source, after)
            if nxt == after:
                return None
            after = nxt
        after = skip_optional(source, after)
        opening = group_start(source, after)
        if opening is None or opening + 1 > stop:
            return None
        at = opening + 1               # just inside the content group's brace
    return min(at, stop)


def _top_level(source: str, start: int, stop: int):
    r"""Yield `(lo, hi, kind)` for cell breaks, row separators and rules at
    brace depth zero.

    Depth matters: `\\` inside a brace group is a line break within one cell,
    not a row separator. `_flatten_stacked_cells` removes the `makecell` case
    before this runs in the render pipeline, but the split must not depend on
    that having happened -- the skills call this module directly.
    """
    depth = 0
    i = start
    while i < stop:
        c = source[i]
        if c == "%":
            nl = source.find("\n", i)
            i = stop if nl == -1 else min(nl + 1, stop)
            continue
        if c == "{":
            depth += 1
            i += 1
            continue
        if c == "}":
            depth -= 1
            i += 1
            continue
        if c == "&":
            if depth == 0:
                yield i, i + 1, "cell"
            i += 1
            continue
        if c != "\\":
            i += 1
            continue
        if depth == 0:
            m = _ROW_SEP_RE.match(source, i, stop)
            if m is not None:
                yield m.start(), m.end(), "rowsep"
                i = m.end()
                continue
            m = _FULL_RULE_RE.match(source, i, stop)
            if m is not None:
                yield m.start(), m.end(), "rule"
                i = m.end()
                continue
        # Any other control sequence, escaped character included: consumed whole
        # so that `\&`, `\%` and `\{` cannot be read as structure.
        m = _CONTROL_RE.match(source, i)
        i = m.end() if m else i + 1


_COMMENT_RE = re.compile(r"(?<!\\)((?:\\\\)*)%[^\n]*")


def strip_comments(text: str) -> str:
    r"""Drop LaTeX comments, leaving escaped `\%` and `\\` alone.

    `\%` is a literal percent sign and starts nothing; `\\%` IS a comment,
    because the backslashes pair off first. The capture group preserves any
    even-numbered run of backslashes that preceded the `%`.
    """
    return _COMMENT_RE.sub(r"\1", text)


def count_table_environments(text: str) -> int:
    r"""How many table environments the LaTeX source actually contains.

    The unit of the post-conversion count guard. Counts the tabular-family
    environments rather than `\begin{table}`, because a float may hold none or
    several and it is the tabular that becomes a table in the output.

    Comments are stripped first. Authors leave superseded column specs commented
    out directly above the live one -- estonia-ecm's balance table carries two
    such ghosts -- and counting them inflates the expected total, which fires
    the guard on a document that is perfectly fine. A guard that cries wolf gets
    switched off, so a false alarm is a real defect and not a safe direction to
    err in.
    """
    return len(TABLE_BEGIN_RE.findall(strip_comments(text)))


_WORD_ALIGN = {"l": "left", "c": "center", "r": "right"}


def expected_alignments(text: str) -> list[list[str]]:
    r"""Per-table column alignments the SOURCE asks for, in document order.

    A list of lists of `"left"`/`"center"`/`"right"`, one per table environment,
    read through the same `\newcolumntype` map the normalizer uses. This is what
    a delivered `.docx` must actually contain: the docx is submitted from, and a
    column silently flipped to right-aligned reads as a formatting choice rather
    than an error, so it survives a human skim all the way to the journal.

    Vertical rules are dropped -- they are not columns.
    """
    declared = declared_column_types(text)
    body = strip_comments(text)
    out: list[list[str]] = []
    for m in TABLE_BEGIN_RE.finditer(body):
        at = skip_optional(body, m.end())
        for _ in range(TABLE_ENVS[m.group(1)]):
            at = skip_group(body, at)
        spec_end = skip_group(body, at)
        start = group_start(body, at)
        if spec_end == at or start is None:
            out.append([])
            continue
        letters = plain_colspec(body[start + 1:spec_end - 1], declared)
        out.append([_WORD_ALIGN[c] for c in letters if c in _WORD_ALIGN])
    return out


_REPEAT_RE = re.compile(r"\*\s*\{\s*(\d+)\s*\}\s*(?=\{)")


def _expand_repeats(spec: str) -> str:
    r"""Expand the `array` package's `*{n}{cols}` repetition.

    This is what Stata's esttab emits by default (`l*{1}{ccccc}`), and pandoc
    does not read it: the table vanishes with no error. estonia-qbs lost five of
    its seven tables to exactly this.

    Dropping the multiplier instead of expanding it is worse than it looks. At
    `*{1}` it happens to be right, so it passes on the common case and then
    quietly discards columns the moment a manuscript uses `*{3}`.
    """
    out = spec
    for _ in range(8):  # bounded: nested repeats are legal but never deep
        m = _REPEAT_RE.search(out)
        if not m:
            break
        end = skip_group(out, m.end())
        inner = out[m.end() + 1:end - 1]
        out = out[:m.start()] + inner * int(m.group(1)) + out[end:]
    return out


def plain_colspec(spec: str, declared: dict[str, str] | None = None) -> str:
    r"""Reduce a column specification to alignment letters and rules.

    Pandoc's tables carry alignment and nothing else, so width, font, and
    inter-column material are all noise. The reduction has to be a parse rather
    than a substitution: `>{\centering\arraybackslash}p{4cm}` contains the
    letters c, r, and l inside a command name, and a character filter would read
    that single column as four.
    """
    spec = _expand_repeats(spec)
    out: list[str] = []
    i = 0
    while i < len(spec):
        c = spec[i]
        if c in "<>@!":
            nxt = skip_group(spec, i + 1)
            i = nxt if nxt > i + 1 else i + 1
            continue
        if c == "[":
            i = skip_optional(spec, i)
            continue
        if c == "|":
            out.append("|")
            i += 1
            continue
        if c.isalpha():
            after = skip_optional(spec, i + 1)
            after = skip_group(spec, after)
            out.append((declared or {}).get(c) or ALIGN.get(c, "l"))
            i = max(after, i + 1)
            continue
        i += 1
    return "".join(out) or "l"


# ------------------------------------------------------- the manifest
#
# Written beside the normalized `.tex` so a post-conversion gate can compare the
# delivered file against what the SOURCE asked for. Without it the gate can only
# compare against an already-stripped file, which cannot detect a strip-only
# normalization -- see the comment in `normalize_tables`.


def write_manifest(out_tex_path, stats: dict) -> Path:
    """Record the source's own alignments beside the normalized `.tex`."""
    path = Path(str(out_tex_path) + MANIFEST_SUFFIX)
    path.write_text(json.dumps({
        "alignments": stats["alignments"],
        "declared": stats["declared"],
    }, indent=1), encoding="utf-8")
    return path


def read_manifest(tex_path) -> dict | None:
    """The manifest beside `tex_path`, or None when it was never written."""
    path = Path(str(tex_path) + MANIFEST_SUFFIX)
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


# ------------------------------------------------- shared LaTeX brace helpers
#
# Not table logic, but every caller of the above needs them and `render/pandoc.py`
# uses the same three to unwrap `\resizebox` and to strip macro definitions.
# They live at the bottom of the module the other users import, rather than in a
# fourth module holding three functions.


def group_start(text: str, at: int) -> int | None:
    i = at
    while i < len(text) and text[i] in " \t\n":
        i += 1
    return i if i < len(text) and text[i] == "{" else None


def skip_optional(text: str, at: int) -> int:
    i = at
    while i < len(text) and text[i] in " \t":
        i += 1
    if i >= len(text) or text[i] != "[":
        return at
    depth = 0
    while i < len(text):
        if text[i] == "[":
            depth += 1
        elif text[i] == "]":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return at


def skip_group(text: str, at: int) -> int:
    r"""Return the offset just past the brace group starting at or after `at`.

    Comments are skipped, because LaTeX skips them and flattening does not strip
    them. A `%` line carrying a lone brace is legal source, and counting it
    would close a group somewhere in the middle of the table it wraps.

    A newline before the brace is skipped too, and an unbalanced group returns
    `at` -- no progress -- rather than the end of the text. Both were points on
    which the two implementations differed. `at` is what every caller here is
    written to expect: each of them tests `end == at` and leaves the construct
    alone, whereas `len(text)` makes an unclosed brace swallow the remainder of
    the document as though it were a column specification.
    """
    i = at
    while i < len(text) and text[i] in " \t\n":
        i += 1
    if i >= len(text) or text[i] != "{":
        return at
    depth = 0
    while i < len(text):
        c = text[i]
        if c == "%":
            nl = text.find("\n", i)
            i = len(text) if nl == -1 else nl + 1
            continue
        if c == "\\" and i + 1 < len(text):
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return at


# ------------------------------------------------------------------ the CLI
#
# `python3 -m manuscriptor.render.tables IN.tex [OUT.tex]`. The Word skills call
# this, and their scripts import the functions above directly.


def _cli(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.exit("usage: python3 -m manuscriptor.render.tables IN.tex [OUT.tex]")
    text = Path(argv[1]).read_text(encoding="utf-8", errors="replace")
    out, stats = normalize_tables(text)
    if len(argv) > 2:
        Path(argv[2]).write_text(out, encoding="utf-8")
        write_manifest(argv[2], stats)
        sys.stderr.write(
            "tables: stripped %d \\newcolumntype declaration(s), rewrote %d "
            "table spec(s) and %d \\multicolumn spec(s)\n"
            % (stats["declarations"], stats["table_specs"],
               stats["multicolumn_specs"]))
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli(sys.argv))
