"""What is lying around beside the manuscript, and which of it is safe to lose.

Manuscriptor now keeps its own files in one hidden directory, which leaves the
question of everything else. The reference case, dsp-bias, holds thirty-four
entries in its `paper/` folder and only two of them were ever Manuscriptor's:
seventeen are `.aux`, `.log`, `.bbl` and `.blg` from the author's own `latexmk`
runs, and the rest are documents, scripts and drafts that belong there.

So this module does not clean. It LOOKS, and it says what it found. The standing
rule in this repository is that automated interaction with a real manuscript
eventually writes to it, and a sweep that runs by default is exactly that. The
author asks for `--sweep` when they have read the list.

**Two questions, kept apart.** Whether a file is regenerable is decided by the
suffix, from the fixed set below. Whether removing it is SAFE is decided by git:
a file git already ignores can be reproduced or was never wanted, and a file git
tracks must never be swept no matter what it is called, because the reference
manuscript has `main.aux`, `main.bbl` and `main.log` COMMITTED. Conflating the
two is how a sweep would delete a tracked file that happens to end in `.log`.

A `.tex` is never listed, never swept, and never considered. Neither is anything
inside the hidden directory, which `manuscriptor clean` owns.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from manuscriptor.server import gitcmd, paths

# Regenerated by running LaTeX again. `.pdf` is deliberately NOT here: it is the
# deliverable, and on many manuscripts it is the only copy anyone has.
LATEX_LITTER = (".aux", ".log", ".blg", ".bbl", ".out", ".toc", ".lof", ".lot",
                ".fls", ".fdb_latexmk", ".synctex.gz", ".nav", ".snm", ".vrb")

# Written by the operating system, never by anybody on purpose.
JUNK_NAMES = (".DS_Store", "Thumbs.db")

NEVER = (".tex", ".bib", ".cls", ".sty", ".bst")


@dataclass(frozen=True)
class Finding:
    path: Path
    why: str
    safe: bool          # git ignores it or does not know it: losing it costs nothing
    reason: str         # why it is or is not safe, in the author's terms

    def line(self) -> str:
        mark = " " if self.safe else "!"
        return f" {mark} {self.path.name:<32} {self.why}; {self.reason}"


def _ignored(root: Path, candidates: list[Path]) -> set[Path]:
    """Which of these git already ignores. Empty outside a repository."""
    if not candidates:
        return set()
    done = gitcmd.run(["check-ignore", "--stdin"], cwd=root,
                      input="\n".join(str(p) for p in candidates))
    if done is None:
        return set()
    return {Path(line) for line in done.stdout.splitlines() if line}


def _tracked(root: Path, candidates: list[Path]) -> set[Path]:
    """Which of these git is tracking. These are never safe to sweep."""
    if not candidates:
        return set()
    done = gitcmd.run(["ls-files", "-z", "--", *[str(p) for p in candidates]],
                      cwd=root)
    if done is None:
        return set()
    return {(root / name).resolve() for name in done.stdout.split("\0") if name}


def scan(manuscript_dir: Path | str) -> list[Finding]:
    """Every stray artifact beside the manuscript, most obvious first."""
    root = Path(manuscript_dir).resolve()
    candidates: list[tuple[Path, str]] = []
    for path in sorted(root.iterdir()):
        if not path.is_file():
            continue
        if paths.HOME in path.parts or path.suffix.lower() in NEVER:
            continue
        if path.name in JUNK_NAMES:
            candidates.append((path, "written by the operating system"))
        elif path.name.endswith(".synctex.gz") or path.suffix.lower() in LATEX_LITTER:
            candidates.append((path, "regenerated by the next LaTeX run"))

    paths_only = [p for p, _ in candidates]
    ignored = _ignored(root, paths_only)
    tracked = _tracked(root, paths_only)

    out: list[Finding] = []
    for path, why in candidates:
        if path.resolve() in tracked:
            out.append(Finding(path, why, False,
                               "git tracks it, so removing it would change the repository"))
        elif path in ignored or not ignored and not tracked:
            out.append(Finding(path, why, True, "git ignores it"))
        else:
            out.append(Finding(path, why, True, "git does not know about it"))
    return out


def sweep(findings: list[Finding]) -> tuple[list[Path], list[Finding]]:
    """Remove the safe ones. Returns what went and what was kept back."""
    gone: list[Path] = []
    kept: list[Finding] = []
    for f in findings:
        if not f.safe:
            kept.append(f)
            continue
        try:
            f.path.unlink()
        except OSError as exc:
            kept.append(Finding(f.path, f.why, False, str(exc)))
            continue
        gone.append(f.path)
    return gone, kept


def report(manuscript_dir: Path | str, findings: list[Finding]) -> str:
    """The whole message, whether or not anything was found."""
    root = Path(manuscript_dir).resolve()
    if not findings:
        return f"nothing stray beside {root.name}"
    safe = [f for f in findings if f.safe]
    lines = [f"{len(findings)} stray file{'s' if len(findings) != 1 else ''} "
             f"beside {root.name}:"]
    lines += [f.line() for f in findings]
    lines.append("")
    if safe:
        lines.append(f"{len(safe)} can be removed with --sweep. "
                     "Lines marked ! are tracked by git and will be left.")
    else:
        lines.append("None can be removed: git tracks all of them.")
    return "\n".join(lines)
